### ISSUE TITLE
Consider override mask for island areas

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#6]
@mojodna Can you add detail here, please?

**Comment by sethfitz** [comment]
[Swains Island](https://4cowg0thg6.execute-api.us-east-1.amazonaws.com/dev/preview#14/-11.0567/-171.0779)

![image](https://user-images.githubusercontent.com/45/46114760-e8406180-c1a8-11e8-8cb2-3af85324a260.png)

**Comment by sethfitz** [comment]
The beach-colored artifacts around the edges are pixels from ESACCI-LC that are partially masked by the C-CAP data. Since the "water" doesn't extend out enough, a solution is to edit the ESACCI-LC mask (which is currently a rectangle covering the world) and cut out holes to prevent this from happening. We can put this edited footprint in `meta` and use it to override the "dataset footprint".

An interesting side-effect of this approach is that datasets can be duplicated with different footprints and colormaps (to differing unified values) to achieve something like #7.

**Comment by sethfitz** [comment]
Capability unlocked in https://github.com/mojodna/marblecutter/commit/a7199c83920c4a87c9e17b8797da4c80a54b23e7

**Comment by sethfitz** [comment]
C-CAP extents were applied as masks to "ESACCI-LC Mid Latitude", per:

https://gist.github.com/mojodna/4930ba18ab3ba668a116a8914009daa6

(the final mask and footprint are included in that gist; they're the inverse of one another)

![image](https://user-images.githubusercontent.com/45/47593828-b51afa80-d92d-11e8-9e23-f032076d4df8.png)
