### ISSUE TITLE
Consider high-latitude versus mid-latitude barren (desert) classification

### ISSUE THREAD

**Issue by nvkelso** [mojodna/marblecutter-land-cover#7]
Data doesn't support this but we could apply a latitude mask here. Tom and I did that on the early Natural Earth landcover work.

**Comment by nvkelso** [comment]
Here's the article:

- http://www.shadedrelief.com/shelton/d.html

![image](https://user-images.githubusercontent.com/853051/46114408-53893400-c1a7-11e8-985d-80f6838a4cea.png)

This results in rosy mid-latitude and blue high-latitude:

Let's start with boxes and then refine the box to a poly poly.

![image](https://user-images.githubusercontent.com/853051/46114437-787da700-c1a7-11e8-8518-423acfb921de.png)

**Comment by sethfitz** [comment]
I was thinking we'd start with ESACCI-LC, since that has global coverage. I've cloned it into 2 sources, "ESACCI-LC High Latitudes" and "ESACCI-LC Mid Latitudes", both of which have the same footprint:

```geojson
{"type":"MultiPolygon","coordinates":[[[[-180,-90],[-180,90],[180,90],[180,-90],[-180,-90]]]]}
```

I don't know what you were thinking about for a cut-off, so perhaps you can generate a pair of MultiPolygon footprints for each "source"?

I think we need to create a new classification in the unified schema ("desert") to complement "barren." Are these the correct classifications to merge into "desert" at mid-latitudes? "Bare areas", "Consolidated bare areas", "Unconsolidated bare areas"

(from the ESACCI-LC correlations in https://github.com/mojodna/marblecutter-land-cover/blob/master/README.md#classification-correlation)

**Comment by nvkelso** [comment]
Here you go: 

- https://gist.github.com/nvkelso/b14f0136598eb2e3f9f79e64181b0b0a

![image](https://user-images.githubusercontent.com/853051/46898296-2d1cf700-ce3d-11e8-88e6-12d0a26042ed.png)

That class merging seems fine to me.

**Comment by sethfitz** [comment]
![image](https://user-images.githubusercontent.com/45/47032317-ebcf6480-d126-11e8-91d9-70845cb08618.png)

**Comment by nvkelso** [comment]
What’s the far northern green? Should we do the same to it?

**Comment by sethfitz** [comment]
I'm not sure--compare a sampled pixel to https://github.com/mojodna/marblecutter-land-cover/blob/d794a4e8ede49f779adb53b0300723dd3a04d5b3/landcover/web.py#L30-L41 in order to figure out what it is.
